### ISSUE TITLE
grafana的json在grafana上不显示

### ISSUE THREAD

**Issue by fency12** [xxd763795151/kafka-exporter#2]
如下图，grafana版本为v9.3.1
<img width="1436" alt="图片" src="https://user-images.githubusercontent.com/19307432/221840343-4a3db085-867d-4d77-b808-d52813db0908.png">
<img width="1440" alt="图片" src="https://user-images.githubusercontent.com/19307432/221840446-b5273d86-1899-42ba-a168-13694e70064a.png">

**Comment by xxd763795151** [comment]
> 如下图，grafana版本为v9.3.1 <img alt="图片" width="1436" src="https://user-images.githubusercontent.com/19307432/221840343-4a3db085-867d-4d77-b808-d52813db0908.png"> <img alt="图片" width="1440" src="https://user-images.githubusercontent.com/19307432/221840446-b5273d86-1899-42ba-a168-13694e70064a.png">

我现在也用了v9.2.6的grafana，版本相差不大，应该不是版本的问题。这个提示看着是不是没配置 名字叫“Prometheus”的数据源的原因. 这个是我的原因，数据源写死了，应该导入的时候选择数据源，可以修改下这个json文件，使用全局替换，把这个数据源改了试试：
![image](https://user-images.githubusercontent.com/19887530/222019838-a281c8af-0491-46a2-8150-dab9a93b50ae.png)

**Comment by xxd763795151** [comment]
> 如下图，grafana版本为v9.3.1 <img alt="图片" width="1436" src="https://user-images.githubusercontent.com/19307432/221840343-4a3db085-867d-4d77-b808-d52813db0908.png"> <img alt="图片" width="1440" src="https://user-images.githubusercontent.com/19307432/221840446-b5273d86-1899-42ba-a168-13694e70064a.png">

可以了，我刚才调整了下，又传了个 https://github.com/xxd763795151/kafka-exporter/blob/main/grafana-select-datasource.json 这个json文件，使用这个grafana-select-datasource.json   ，导入的时候可以选择prometheus数据源，你选择自己的那个就行了.

**Comment by fency12** [comment]
大佬威武，果然好使！点赞！
